[env]
TERM = "screen-256color"

[font]
size = 28



# [font.bold]
# style = "Bold"

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# make Option behave like normal Alt key (keys below are made for Swiss german layout)
[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
chars = "#"

[[keyboard.bindings]]
key = "Key7"
mods = "Shift | Alt"
chars = "\\"

[[keyboard.bindings]]
key = "a" 
mods = "Alt" 
action = "None" 

[[keyboard.bindings]]
key = "Key8"
mods = "Alt"
chars = "{"

[[keyboard.bindings]]
key = "Key9"
mods = "Alt"
chars = "}"
[[keyboard.bindings]]
key = "n"
mods = "Alt"
chars = "~"

[[keyboard.bindings]]
key = "Key5"
mods = "Alt"
chars = "["

[[keyboard.bindings]]
key = "Key6"
mods = "Alt"
chars = "]"

[[keyboard.bindings]]
key = "Key7"
mods = "Alt"
chars = "|"

[[keyboard.bindings]]
key = "^"
mods = "Alt"
chars = "Â´"

# [[keyboard.bindings]]
# chars = "\u001BOH"
# key = "Left"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001BOF"
# key = "Right"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u0015"
# key = "Back"
# mods = "Command

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "A"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "B"
mode = "~Search"
mods = "Command"

[window]
opacity = 1.0
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Fullscreen"

[window.padding]
x = 0
y = 50

[general]
import = ["themes/bloodmoon.toml"]
