# Reference: https://github.com/i3/i3/blob/next/etc/config

# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

start-at-login = true

[mode.main.binding]
    # See: https://nikitabobko.github.io/AeroSpace/goodies#open-a-new-window-with-applescript

    alt-j = 'move left'
    alt-shift-k = 'move down'
    alt-shift-l = 'move up'
    alt-shift-semicolon = 'move right'

    # Consider using 'join-with' command as a 'split' replacement if you want to enable
    # normalizations
    alt-h = 'split horizontal'

    alt-f = 'fullscreen'

    alt-d = 'exec-and-forget open -a Finder'
    alt-b = 'exec-and-forget open -a /Applications/Firefox.app'
    alt-a = 'exec-and-forget open -a /Applications/Alacritty.app'
    alt-t = 'exec-and-forget open -a /Applications/Microsoft\ Teams.app'
    alt-o = 'exec-and-forget open -a /Applications/Microsoft\ OneNote.app'
    alt-p = 'exec-and-forget open -a /Applications/PDF\ Expert.app'
    alt-y = 'exec-and-forget open -a /Applications/System\ Settings.app'
    alt-comma = 'exec-and-forget open -a /Applications/Spotify.app'
    
    alt-shift-r = ['exec-and-forget /opt/homebrew/bin/sketchybar --reload']
    
    #alt-s = 'layout v_accordion' # 'layout stacking' in i3
    alt-w = 'layout h_accordion' # 'layout tabbed' in i3
    alt-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

    alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

    # Not supported, because this command is redundant in AeroSpace mental model.
    # See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
    #alt-space = 'focus toggle_tiling_floating'

    # `focus parent`/`focus child` are not yet supported, and it's not clear whether they
    # should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
    # alt-a = 'focus parent'

    cmd-alt-1 = 'workspace 1'
    cmd-alt-2 = 'workspace 2'
    cmd-alt-3 = 'workspace 3'
    cmd-alt-4 = 'workspace 4'
    cmd-alt-5 = 'workspace 5'

    alt-shift-c = 'reload-config'

    alt-m = 'mode move'

[workspace-to-monitor-force-assignment]

1 = 'main'

2 = 'main'

3 = 'main'

4 = ['secondary', 'main']

5 = ['secondary', 'main']


[mode.move.binding]
    1 = 'move-node-to-workspace 1'
    2 = 'move-node-to-workspace 2'
    3 = 'move-node-to-workspace 3'
    4 = 'move-node-to-workspace 4'
    5 = 'move-node-to-workspace 5'
    
    h = "move-node-to-monitor left"
    j = "move-node-to-monitor right"
    b = 'move-node-to-workspace B'
    t = 'move-node-to-workspace T'
    w = 'move-node-to-workspace W'
    
    enter = 'mode main'
    esc = 'mode main'


